services:
  mysql-master:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: master-password
    volumes:
      - ./docker/master.sql:/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --init-file /init.sql
  mysql-slave:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: slave-password
    volumes:
      - ./docker/slave.sql:/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --init-file /init.sql
  php:
    depends_on:
      - mysql-master
      - mysql-slave
    build:
      context: ./docker/php
    volumes:
      - ./mysql-replication-check.php:/mysql-replication-check.php
    command: sleep infinity
