services:
  mysql-master:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: master-password
    volumes:
      - ./docker/master.sql:/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --init-file /init.sql
  mysql-slave:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: slave-password
    volumes:
      - ./docker/slave.sql:/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --init-file /init.sql
  php:
    depends_on:
      - mysql-master
      - mysql-slave
    build:
      context: ./docker/php
    volumes:
      - ./mysql-replication-check.php:/mysql-replication-check.php
    command: sleep infinity
  php-psalm:
    build:
      context: ./docker/php-psalm
    volumes:
      - ./docker/php-psalm/composer.json:/app/composer.json
      - ./docker/php-psalm/psalm.xml:/app/psalm.xml
      - ./mysql-replication-check.php:/app/mysql-replication-check.php
    working_dir: /app
    command: ["sh", "-c", "composer install && sleep infinity"]
